parameters:
#    namshi_google_doc_configuration.example.class: Namshi\GoogleDocConfigurationBundle\Example

services:
#    namshi_google_doc_configuration.example:
#        class: %namshi_google_doc_configuration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
